LOCAL_PATH:= $(call my-dir)

# ViaBrowserCN
include $(CLEAR_VARS)
LOCAL_MODULE := ViaBrowserCN
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Jelly
include $(BUILD_PREBUILT)

# SougouIME-Mi
include $(CLEAR_VARS)
LOCAL_MODULE := SougouIME-Mi
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := LatinIME
include $(BUILD_PREBUILT)

# Coolapk
include $(CLEAR_VARS)
LOCAL_MODULE := Coolapk
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GeometricWeather
include $(CLEAR_VARS)
LOCAL_MODULE := GeometricWeather
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)